project:
  type: book
  output-dir: docs

book:
  title: "COMP/STAT112 Notebook"
  author: "Khaleesi Chen"
  date: "9/10"
  reader-mode: true
  
  chapters:
    - index.qmd

    - part: activities/README.qmd
      chapters: 
      - activities/activity-01.qmd
      - activities/activity-02.qmd
      - activities/activity-03.qmd
      - activities/03-univariate-viz-notes.qmd
      - activities/activity-04.qmd
      - activities/activity-05.qmd
      - activities/activity-06.qmd
      - activities/activity-08.qmd
      - activities/activity-07.qmd
      - activities/activity-12.qmd
     
    
    - part: notes/README.qmd
      chapters: 
      - notes/note-01.qmd
      - notes/note-02.qmd
      - notes/note-03.qmd
      - notes/note-04.qmd
      - notes/note-05.qmd
      - notes/note-07.qmd
      

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
    code-line-numbers: true
    code-tools: true

execute:
  cache: false
  freeze: auto
